In [77]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [78]:
data_path = ("C:/Personal/09142640/Desktop/Useful docs/Data science/amazon_sentiment.txt")
sms_raw = pd.read_csv(data_path, delimiter= '\t', header=None)

In [79]:
sms_raw.columns=["Text","Sentiments"]

# Original features in Classifier

In [80]:
positive_keywords = ['seamlessly','satisfied', 'happy', 'enjoyed', 'loved', 'prompt', 'great', 'excellent', 'favorite','good','amazing', 'delicious', 'right', 'love','like','recommended']
negative_keywords = ['angry', 'slow', 'sucks', 'bad', 'disappointed', 'rude', 'avoid', 'never', 'waste','never', 'mistake', 'not good', 'not like', 'zero', 'dirty', 'bland','disaster','downside', 'joke']

In [81]:
for key in positive_keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    sms_raw[str(key)] = sms_raw.Text.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

In [82]:
data = sms_raw[positive_keywords]
target = sms_raw['Sentiments']


In [83]:
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

# Display our results.
print("Number of unmatched positive statements out of a total {} points : {}".format(
    data.shape[0],
    (target != y_pred).sum()
))

Number of unmatched positive statements out of a total 1001 points : 399


In [84]:
from sklearn.metrics import confusion_matrix
C=confusion_matrix(target, y_pred)
print("Sensitivity value : ", C[1,1] / (C[1,0]+C[1,1]) )
print("Specificity  value : ", C[0,0] / (C[0,0]+C[0,1]) )

Sensitivity value :  0.25
Specificity  value :  0.9520958083832335


# Holdout Groups

In [85]:
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data, target).score(data, target)))

With 20% Holdout: 0.6019900497512438
Testing on Sample: 0.6013986013986014


# Cross Validation

In [86]:
from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.6039604, 0.6      , 0.61     , 0.6      , 0.61     , 0.62     ,
       0.62     , 0.53     , 0.62     , 0.56     ])

# Modiying the classifier-Adding capitalised classifiers

In [87]:
positive_keywords = ['seamlessly','satisfied', 'happy', 'enjoyed', 'loved', 'prompt', 'great', 'excellent', 'favorite','good','amazing', 'delicious', 'right', 'love','like','recommended','Seamlessly','Satisfied', 'Happy', 'Enjoyed', 'Loved', 'Prompt', 'Great', 'Excellent', 'Favorite','Good','Amazing', 'Delicious', 'Right', 'Love','Like','Recommended']
negative_keywords = ['angry', 'slow', 'sucks', 'bad', 'disappointed', 'rude', 'avoid', 'never', 'waste','never', 'mistake', 'not good', 'not like', 'zero', 'dirty', 'bland','disaster','downside', 'joke','Angry', 'Slow', 'Sucks', 'Bad', 'Disappointed', 'Rude', 'Avoid', 'Never', 'Waste','Never', 'Mistake', 'Not Good', 'Not Like', 'Zero', 'Dirty', 'Bland','Disaster','Downside', 'Joke']

In [88]:
for key in positive_keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    sms_raw[str(key)] = sms_raw.Text.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

In [89]:
data = sms_raw[positive_keywords]
target = sms_raw['Sentiments']

In [90]:
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

# Display our results.
print("Number of unmatched positive statements out of a total {} points : {}".format(
    data.shape[0],
    (target != y_pred).sum()
))

Number of unmatched positive statements out of a total 1001 points : 399


In [91]:
from sklearn.metrics import confusion_matrix
D=confusion_matrix(target, y_pred)
print("Sensitivity value : ", D[1,1] / (D[1,0]+D[1,1]) )
print("Specificity  value : ", D[0,0] / (D[0,0]+D[0,1]) )

Sensitivity value :  0.25
Specificity  value :  0.9520958083832335


# Holdout Groups

In [92]:
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data, target).score(data, target)))

With 20% Holdout: 0.6019900497512438
Testing on Sample: 0.6013986013986014


# Cross Validation

In [93]:
from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.6039604, 0.6      , 0.61     , 0.6      , 0.61     , 0.62     ,
       0.62     , 0.53     , 0.62     , 0.56     ])

# Modiying the classifiers again 2nd time

In [94]:
positive_keywords = ['convenient','friendly','easy','fine','seamlessly','satisfied', 'happy', 'enjoyed', 'loved', 'prompt', 'great', 'excellent', 'favorite','good','amazing', 'delicious', 'right', 'love','like','recommended','Seamlessly','Satisfied', 'Happy', 'Enjoyed', 'Loved', 'Prompt', 'Great', 'Excellent', 'Favorite','Good','Amazing', 'Delicious', 'Right', 'Love','Like','Recommended']
negative_keywords = ['angry', 'slow', 'sucks', 'bad', 'disappointed', 'rude', 'avoid', 'never', 'waste','never', 'mistake', 'not good', 'not like', 'zero', 'dirty', 'bland','disaster','downside', 'joke','Angry', 'Slow', 'Sucks', 'Bad', 'Disappointed', 'Rude', 'Avoid', 'Never', 'Waste','Never', 'Mistake', 'Not Good', 'Not Like', 'Zero', 'Dirty', 'Bland','Disaster','Downside', 'Joke']

In [95]:
for key in positive_keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    sms_raw[str(key)] = sms_raw.Text.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

In [63]:
data = sms_raw[positive_keywords]
target = sms_raw['Sentiments']

In [96]:
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

# Display our results.
print("Number of unmatched positive statements out of a total {} points : {}".format(
    data.shape[0],
    (target != y_pred).sum()
))

Number of unmatched positive statements out of a total 1001 points : 399


In [65]:
from sklearn.metrics import confusion_matrix
E=confusion_matrix(target, y_pred)
print("Sensitivity value : ", E[1,1] / (E[1,0]+E[1,1]) )
print("Specificity  value : ", E[0,0] / (E[0,0]+E[0,1]) )

Sensitivity value :  0.282
Specificity  value :  0.9461077844311377


# Holdout Groups

In [97]:
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data, target).score(data, target)))

With 20% Holdout: 0.6019900497512438
Testing on Sample: 0.6013986013986014


# Cross Validation

In [98]:
from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.6039604, 0.6      , 0.61     , 0.6      , 0.61     , 0.62     ,
       0.62     , 0.53     , 0.62     , 0.56     ])

# Removing the capitalised classifiers and adding more classifiers 3rd time

In [99]:
positive_keywords = ['impressed','cool','convenient','friendly','easy','fine','seamlessly','satisfied', 'happy', 'enjoyed', 'loved', 'prompt', 'great', 'excellent', 'favorite','good','amazing', 'delicious', 'right', 'love','like','recommended']
negative_keywords = ['angry', 'slow', 'sucks', 'bad', 'disappointed', 'rude', 'avoid', 'never', 'waste','never', 'mistake', 'not good', 'not like', 'zero', 'dirty', 'bland','disaster','downside', 'joke','Angry', 'Slow', 'Sucks', 'Bad', 'Disappointed', 'Rude', 'Avoid', 'Never', 'Waste','Never', 'Mistake', 'Not Good', 'Not Like', 'Zero', 'Dirty', 'Bland','Disaster','Downside', 'Joke']

In [101]:
for key in positive_keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    sms_raw[str(key)] = sms_raw.Text.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

In [102]:
data = sms_raw[positive_keywords]
target = sms_raw['Sentiments']

In [103]:
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

# Display our results.
print("Number of unmatched positive statements out of a total {} points : {}".format(
    data.shape[0],
    (target != y_pred).sum()
))

Number of unmatched positive statements out of a total 1001 points : 383


# Holdout Groups

In [104]:
from sklearn.metrics import confusion_matrix
F=confusion_matrix(target, y_pred)
print("Sensitivity value : ", F[1,1] / (F[1,0]+F[1,1]) )
print("Specificity  value : ", F[0,0] / (F[0,0]+F[0,1]) )

Sensitivity value :  0.296
Specificity  value :  0.93812375249501


# Cross Validation

In [105]:
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data, target).score(data, target)))

With 20% Holdout: 0.6069651741293532
Testing on Sample: 0.6173826173826173


In [106]:
from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.62376238, 0.6       , 0.61      , 0.6       , 0.61      ,
       0.61      , 0.65      , 0.57      , 0.63      , 0.59      ])

# Adding more classifiers 4th time

In [112]:
positive_keywords = ['fixes','Easy','outperform','AWESOME','high quality','impressed','cool','convenient','friendly','easy','fine','seamlessly','satisfied', 'happy', 'enjoyed', 'loved', 'prompt', 'great', 'excellent', 'favorite','good','amazing', 'delicious', 'right', 'love','like','recommended']
negative_keywords = ['angry', 'slow', 'sucks', 'bad', 'disappointed', 'rude', 'avoid', 'never', 'waste','never', 'mistake', 'not good', 'not like', 'zero', 'dirty', 'bland','disaster','downside', 'joke','Angry', 'Slow', 'Sucks', 'Bad', 'Disappointed', 'Rude', 'Avoid', 'Never', 'Waste','Never', 'Mistake', 'Not Good', 'Not Like', 'Zero', 'Dirty', 'Bland','Disaster','Downside', 'Joke']

In [117]:
for key in positive_keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    sms_raw[str(key)] = sms_raw.Text.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

In [118]:
data = sms_raw[positive_keywords]
target = sms_raw['Sentiments']

In [119]:
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

# Display our results.
print("Number of unmatched positive statements out of a total {} points : {}".format(
    data.shape[0],
    (target != y_pred).sum()
))

Number of unmatched positive statements out of a total 1001 points : 379


In [120]:
from sklearn.metrics import confusion_matrix
G=confusion_matrix(target, y_pred)
print("Sensitivity value : ", G[1,1] / (G[1,0]+G[1,1]) )
print("Specificity  value : ", G[0,0] / (G[0,0]+G[0,1]) )

Sensitivity value :  0.304
Specificity  value :  0.93812375249501


# Holdout Groups

In [121]:
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data, target).score(data, target)))

With 20% Holdout: 0.6069651741293532
Testing on Sample: 0.6213786213786214


# Cross Validation

In [122]:
from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.62376238, 0.6       , 0.61      , 0.6       , 0.61      ,
       0.61      , 0.65      , 0.57      , 0.63      , 0.59      ])

# Conclusion 

Adding more features in the last iteration of  classifiers outperformed all the other classifiers
Do any of your classifiers seem to overfit?If we use all the data in our training set,overfitting will occur.Since we are training the model with all the data multiple times.There is ovefitting error.
Which seem to perform the best? Why?The last iteration seem to perfomed the data interms of accuracy and performance
Which features seemed to be most impactful to performance? Adding new features and capitalising existing features impacted the performance to improve in the model