In [1]:
import math
import warnings
from datetime import datetime
start=datetime.now()
from IPython.display import display
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import linear_model
import statsmodels.formula.api as smf
from sklearn.model_selection import cross_val_score
from sklearn import neighbors
from sklearn import tree,model_selection
from sklearn.grid_search import GridSearchCV
# A convenience for displaying visualizations.
from IPython.display import Image
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn import preprocessing
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# Display preferences.
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [2]:
# Suppress annoying harmless error.
warnings.filterwarnings(
    action="ignore",
    module="scipy",
    message="^internal gelsd"
)

from sklearn import ensemble
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
start=datetime.now()
rfc = ensemble.RandomForestClassifier()


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [3]:
data = pd.read_csv('C:/Personal/09142640/Downloads/Car_sales_U.csv')
data.columns.values[3]='Year_Resale_Value'
data_req=data.loc[:,["Sales_in_thousands","Year_Resale_Value","Price_in_thousands","Engine_size","Horsepower","Wheelbase","Width","Length","Curb_weight","Fuel_capacity","Fuel_efficiency","Power_perf_factor"]]
data_na=data_req.fillna(0)


In [4]:
Y = data_na[['Sales_in_thousands']].astype('int')
X = data_na.drop(columns='Sales_in_thousands').astype('int')
X.head(5)


Year_Resale_Value  Price_in_thousands  Engine_size  Horsepower  Wheelbase  \
0                 16                  21            1         140        101   
1                 19                  28            3         225        108   
2                 18                   0            3         225        106   
3                 29                  42            3         210        114   
4                 22                  23            1         150        102   

   Width  Length  Curb_weight  Fuel_capacity  Fuel_efficiency  \
0     67     172            2             13               28   
1     70     192            3             17               25   
2     70     192            3             17               26   
3     71     196            3             18               22   
4     68     178            2             16               27   

   Power_perf_factor  
0                 58  
1                 91  
2                  0  
3                 91  
4                 62

In [5]:
# gridsearchCV
#Then do holdout and cross validation for the decision tree
#Then Classification report
#Then use pca and select kbest  to feature selection/reduction
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=1)
rfc = ensemble.RandomForestClassifier()
dt_grid={'max_depth':[3,4,5],'criterion':['gini','entropy']}
grid_class=model_selection.GridSearchCV(rfc,dt_grid,cv=6)
grid_class.fit(X_train, y_train)


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=6.
  % (min_groups, self.n_splits)), Warning)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-

C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:740: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


GridSearchCV(cv=6, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'max_depth': [3, 4, 5], 'criterion': ['gini', 'entropy']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [6]:
#Displaying the parameters using Grid search
results = grid_class.cv_results_
print(results.get('params'))
print(results.get('mean_test_score'))
print(results.get('mean_train_score'))
print(grid_class.best_params_)
print(grid_class.best_score_)
final_model = grid_class.best_estimator_
print(final_model)


[{'criterion': 'gini', 'max_depth': 3}, {'criterion': 'gini', 'max_depth': 4}, {'criterion': 'gini', 'max_depth': 5}, {'criterion': 'entropy', 'max_depth': 3}, {'criterion': 'entropy', 'max_depth': 4}, {'criterion': 'entropy', 'max_depth': 5}]
[0.02564103 0.04273504 0.05128205 0.02564103 0.02564103 0.04273504]
[0.38898625 0.47489009 0.58377922 0.45917496 0.71914545 0.87852368]
{'criterion': 'gini', 'max_depth': 5}
0.05128205128205128
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)


In [7]:
#Displaying the accuracy scores using the training data
Random_f = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=4, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

#decision_tree.fit(X_train, y_train)
Random_f.fit(X_train, y_train)
print(Random_f.feature_importances_)


[0.1326604  0.09162165 0.06077499 0.1067697  0.13146895 0.07701411
 0.12363889 0.05738379 0.06931819 0.04737614 0.10197319]


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


In [8]:
#Cross validation-
cross_val_score(rfc, X, Y, cv=6)

#holdout and cross validation for the decision tree
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.4, random_state=20)
print('With 40% Holdout: ' + str(Random_f.fit(X_train, y_train.astype('int')).score(X_test, y_test.astype('int'))))
print('Testing on Sample: ' + str(Random_f.fit(X, Y.astype('int')).score(X, Y.astype('int'))))


With 40% Holdout: 0.015873015873015872
Testing on Sample: 0.33974358974358976


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=6.
  % (min_groups, self.n_splits)), Warning)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-

In [9]:
#Classification Report for finding the Text summary of the precision, recall, F1 score for each class
ypred = Random_f.predict(X_train)
from sklearn import metrics
print(metrics.classification_report(ypred, y_train))


             precision    recall  f1-score   support

          0       1.00      0.67      0.80         3
          1       0.83      0.83      0.83         6
          3       0.67      0.67      0.67         3
          5       0.00      0.00      0.00         2
          8       0.00      0.00      0.00         0
          9       0.50      0.50      0.50         4
         11       1.00      1.00      1.00         1
         12       0.33      1.00      0.50         1
         13       0.00      0.00      0.00         0
         14       0.00      0.00      0.00         0
         16       0.33      1.00      0.50         1
         17       0.50      1.00      0.67         1
         19       0.00      0.00      0.00         0
         20       0.00      0.00      0.00         0
         21       0.00      0.00      0.00         0
         22       1.00      1.00      1.00         1
         24       0.00      0.00      0.00         4
         26       0.50      0.07      0.12   

C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [10]:
#Using PCA

features_pca =data.loc[:,["Year_Resale_Value","Price_in_thousands","Engine_size","Horsepower","Wheelbase","Width","Length","Curb_weight","Fuel_capacity","Fuel_efficiency","Power_perf_factor"]].fillna(0)

# The NumPy covariance function assumes that variables are reprensented by rows, not columns, so we transpose X.
Xt = X_train.T
Cx = np.cov(Xt)
print('Covariance Matrix:\n', Cx)


Covariance Matrix:
 [[ 1.62930108e+02  1.76553997e+02  7.69810659e+00  6.18773492e+02
  -7.06872370e+00  1.01694717e+01 -3.90404395e+00  2.65883590e+00
   1.37633240e+01 -2.39967274e+01  2.88340229e+02]
 [ 1.76553997e+02  2.31786115e+02  1.17037167e+01  8.40145512e+02
   3.80680224e+00  1.93741234e+01  2.28194250e+01  4.69424965e+00
   2.51276297e+01 -3.53551893e+01  3.89046985e+02]
 [ 7.69810659e+00  1.17037167e+01  1.43267882e+00  6.54488079e+01
   3.83064516e+00  3.01157083e+00  7.57924264e+00  5.31556802e-01
   3.29137447e+00 -4.03541374e+00  2.80406732e+01]
 [ 6.18773492e+02  8.40145512e+02  6.54488079e+01  4.19682679e+03
   1.26944250e+02  1.39596774e+02  3.29881136e+02  2.28765778e+01
   1.37318373e+02 -1.88995792e+02  1.82575421e+03]
 [-7.06872370e+00  3.80680224e+00  3.83064516e+00  1.26944250e+02
   6.59810659e+01  1.95673212e+01  9.40312062e+01  3.30119215e+00
   2.39284712e+01 -2.06823282e+01  4.76654979e+01]
 [ 1.01694717e+01  1.93741234e+01  3.01157083e+00  1.39596774e+02

In [11]:
X_pca = StandardScaler().fit_transform(features_pca)
eig_val_cov, eig_vec_cov = np.linalg.eig(Cx)


In [12]:
sklearn_pca = PCA(n_components=11)
x_sklearn = sklearn_pca.fit_transform(X_pca)
#regr.fit(x_sklearn, Y)
print(
    'The percentage of total variance in the dataset explained by each',
    'component from Sklearn PCA.\n',
    sklearn_pca.explained_variance_ratio_
)


The percentage of total variance in the dataset explained by each component from Sklearn PCA.
 [0.5798994  0.2090275  0.06302122 0.04172858 0.03014566 0.02441164
 0.01946664 0.01198268 0.01101651 0.00693254 0.00236763]


By using PCA, we can see the first 2 features are closely correlated to the output variable so we will keep them
Now we will use these models after doing PCA-

1.GridsearchCV

2.Holdout and cross validation

3.Classification report


In [13]:
#X and Y variables after evaluating PCA
Y_pca = data_na[['Sales_in_thousands']].astype('int')
X_pca_fea = data_na[["Year_Resale_Value","Price_in_thousands"]].astype('int')


In [14]:
#using training and test data
from sklearn.model_selection import train_test_split

X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca_fea, Y_pca, random_state=1)


In [15]:
# Using Random Forest Classifier model
random_f_pca = RandomForestClassifier(
    criterion='entropy',
    max_features=2,
    max_depth=4
)


In [16]:
#Using Grid search  for finding the best set of parameters with random Forest model
dt_grid_pca={'max_depth':[3,4,5],'criterion':['gini','entropy']}
grid_class_pca=model_selection.GridSearchCV(random_f_pca,dt_grid_pca,refit=True,return_train_score=True)
grid_class_pca.fit(X_train_pca, y_train_pca)
#Displaying the parameters using Grid search
results_pca = grid_class_pca.cv_results_
print(results_pca.get('params'))
print(results_pca.get('mean_test_score'))
print(results_pca.get('mean_train_score'))
print(grid_class_pca.best_params_)
print(grid_class_pca.best_score_)
final_model_pca = grid_class_pca.best_estimator_
print(final_model_pca)


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-

[{'criterion': 'gini', 'max_depth': 3}, {'criterion': 'gini', 'max_depth': 4}, {'criterion': 'gini', 'max_depth': 5}, {'criterion': 'entropy', 'max_depth': 3}, {'criterion': 'entropy', 'max_depth': 4}, {'criterion': 'entropy', 'max_depth': 5}]
[0.04273504 0.05982906 0.05128205 0.04273504 0.04273504 0.06837607]
[0.39754989 0.49411655 0.61509547 0.3772567  0.63386564 0.79121458]
{'criterion': 'entropy', 'max_depth': 5}
0.06837606837606838
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=5, max_features=2, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anacond

In [17]:
#holdout and cross validation for the decision tree after PCA
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(X_pca_fea, Y_pca, test_size=0.4, random_state=40)
print('With 40% Holdout: ' + str(random_f_pca.fit(X_train, y_train.astype('int')).score(X_test, y_test.astype('int'))))
print('Testing on Sample: ' + str(random_f_pca.fit(X_pca_fea, Y_pca.astype('int')).score(X_pca_fea, Y_pca.astype('int'))))


With 40% Holdout: 0.031746031746031744
Testing on Sample: 0.36538461538461536


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [18]:
#Cross Vaidation to get the accuracy
from sklearn.model_selection import cross_val_score
cross_val_score(random_f_pca, X_pca_fea, Y_pca.astype('int'), cv=6)


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=6.
  % (min_groups, self.n_splits)), Warning)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-

array([0.02272727, 0.02702703, 0.        , 0.        , 0.33333333,
       0.        ])

In [19]:
#Classification Report for finding the Text summary of the precision, recall, F1 score for each class
ypred = random_f_pca.predict(X_test)
from sklearn import metrics
print(metrics.classification_report(ypred, y_test))


             precision    recall  f1-score   support

          0       0.00      0.00      0.00         0
          1       1.00      0.43      0.60         7
          3       0.00      0.00      0.00         0
          4       1.00      0.50      0.67         2
          5       0.50      1.00      0.67         1
          7       0.00      0.00      0.00         0
          8       0.50      1.00      0.67         1
          9       0.00      0.00      0.00         0
         11       0.00      0.00      0.00         1
         12       1.00      1.00      1.00         2
         13       1.00      1.00      1.00         1
         14       1.00      0.67      0.80         3
         16       1.00      1.00      1.00         1
         18       0.00      0.00      0.00         1
         19       0.00      0.00      0.00         0
         20       0.00      0.00      0.00         0
         21       1.00      0.50      0.67         2
         23       0.00      0.00      0.00   

C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [20]:
#X and Y variables for selectkbest
Y = data_na[['Sales_in_thousands']].astype('int')
X = data_na.drop(columns='Sales_in_thousands').astype('int')
from sklearn.model_selection import train_test_split
import numpy
#Y=Y.reshape(-1,1)
#X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=1)
#sel_kbest = SelectKBest(f_classif, k=2).fit(X_train, y_train)


In [21]:
#selectkbest
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=1)
names = ["Year_Resale_Value","Price_in_thousands","Engine_size","Horsepower","Wheelbase","Width","Length","Curb_weight","Fuel_capacity","Fuel_efficiency","Power_perf_factor"]
for n in range(0, len(names)):
    test = SelectKBest(score_func=chi2, k=2)
    fit = test.fit(X_train, y_train)
    print(names[n], fit.scores_[n])


Year_Resale_Value 646.3153531955787
Price_in_thousands 597.5343790637187
Engine_size 33.06132075471699
Horsepower 1313.1779550448628
Wheelbase 47.00355147645648
Width 14.059999999999999
Length 80.86056440933375
Curb_weight 14.55060422960725
Fuel_capacity 59.95788310412573
Fuel_efficiency 95.03265563152219
Power_perf_factor 632.869515076508


Using selectkbest , we have got 2 best features-"Year_Resale_Value","Horsepower". Now we will use these models after doing selectkbest-

1.GridsearchCV

2.Holdout and cross validation

3.Classification report


In [22]:
#Creating X and Y variable for further analysis
Y_skb = data_na[['Sales_in_thousands']].astype('int')
X_skb = data_na[["Year_Resale_Value","Horsepower"]].astype('int')


In [23]:
#using training and test data
from sklearn.model_selection import train_test_split

X_train_skb, X_test_skb, y_train_skb, y_test_skb = train_test_split(X_skb, Y_skb, random_state=1)


random_f_skb = RandomForestClassifier(
    criterion='entropy',
    max_features=2,
    max_depth=4
)


In [24]:
dt_grid_skb={'max_depth':[3,4,5],'criterion':['gini','entropy']}
grid_class_skb=model_selection.GridSearchCV(random_f_skb,dt_grid_skb,refit=True,cv=2,return_train_score=True)
grid_class_skb.fit(X_train_skb, y_train_skb)


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2.
  % (min_groups, self.n_splits)), Warning)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-

GridSearchCV(cv=2, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=4, max_features=2, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'max_depth': [3, 4, 5], 'criterion': ['gini', 'entropy']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [25]:
#Displaying the parameters using Grid search
results = grid_class_skb.cv_results_
print(results.get('params'))
print(results.get('mean_test_score'))
print(results.get('mean_train_score'))
print(grid_class.best_params_)
print(grid_class.best_score_)
final_model = grid_class_skb.best_estimator_
print(final_model)


[{'criterion': 'gini', 'max_depth': 3}, {'criterion': 'gini', 'max_depth': 4}, {'criterion': 'gini', 'max_depth': 5}, {'criterion': 'entropy', 'max_depth': 3}, {'criterion': 'entropy', 'max_depth': 4}, {'criterion': 'entropy', 'max_depth': 5}]
[0.04273504 0.04273504 0.03418803 0.01709402 0.02564103 0.00854701]
[0.50073529 0.52040441 0.68860294 0.44779412 0.77279412 0.89025735]
{'criterion': 'gini', 'max_depth': 5}
0.05128205128205128
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features=2, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


In [26]:

#using the parameters in random forest model
random_f_skb = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features=2, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


In [27]:
#decision_tree.fit(X_train, y_train)
random_f_skb.fit(X_train_skb, y_train_skb)


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features=2, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [29]:
#holdout and cross validation for the decision tree after PCA
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train_skb, X_test_skb, y_train_skb, y_test_skb = train_test_split(X_skb, Y_skb, test_size=0.4, random_state=40)
print('With 40% Holdout: ' + str(random_f_skb.fit(X_train_skb, y_train_skb.astype('int')).score(X_test_skb, y_test_skb.astype('int'))))
print('Testing on Sample: ' + str(random_f_skb.fit(X_skb, Y_skb.astype('int')).score(X_skb, Y_skb.astype('int'))))


With 40% Holdout: 0.047619047619047616
Testing on Sample: 0.21794871794871795


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [30]:
#Cross Vaidation
from sklearn.model_selection import cross_val_score
cross_val_score(random_f_skb, X_skb, Y_skb, cv=6)


C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=6.
  % (min_groups, self.n_splits)), Warning)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-

array([0.01136364, 0.        , 0.        , 0.        , 0.33333333,
       0.        ])

In [31]:
#Classification Report for finding the Text summary of the precision, recall, F1 score for each class
ypred = random_f_skb.predict(X_test_skb)
from sklearn import metrics
print(metrics.classification_report(ypred, y_test_skb))


             precision    recall  f1-score   support

          0       1.00      1.00      1.00         1
          1       0.67      0.67      0.67         3
          3       0.00      0.00      0.00         2
          4       0.00      0.00      0.00         0
          5       0.50      1.00      0.67         1
          7       0.00      0.00      0.00         0
          8       0.50      1.00      0.67         1
          9       1.00      0.50      0.67         2
         11       0.00      0.00      0.00         0
         12       0.00      0.00      0.00         0
         13       0.00      0.00      0.00         0
         14       0.00      0.00      0.00         1
         15       0.00      0.00      0.00         1
         16       0.00      0.00      0.00         0
         19       0.00      0.00      0.00         0
         20       0.00      0.00      0.00         0
         21       0.00      0.00      0.00         0
         23       0.00      0.00      0.00   

C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\09142640\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [32]:
#Total time took to run the entire model
print(datetime.now()-start)


0:21:58.050000


# Conclusion:

Decision Tree and Random Forest are being further analysed using Holdout and cross validation,gridsearchCV,Classification report techniques and then with feature selections techniques such as PCA,Selectkbest Feature selection using PCA looks to be more accurate and provide more consistent results as compared to selectkbest.This applies to both Decision Tree and Random Forest.Decision Tree is more accurate than Random Forest.The Random Forest took less time than Decision tree, so Random Forest has performance better than Decision Tree