In [1]:

import math
import warnings
from datetime import datetime
start=datetime.now()
from IPython.display import display
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import linear_model
import statsmodels.formula.api as smf
from sklearn.model_selection import cross_val_score
from sklearn import neighbors
from sklearn import tree,model_selection
from sklearn.grid_search import GridSearchCV
# A convenience for displaying visualizations.
from IPython.display import Image
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn import preprocessing
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_decomposition import PLSRegression
import seaborn as sns
import time
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsClassifier
# Display preferences.
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format

# Suppress annoying harmless error.
warnings.filterwarnings(
    action="ignore",
    module="scipy",
    message="^internal gelsd"
)

from sklearn import ensemble
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
start=datetime.now()
rfc = ensemble.RandomForestClassifier()
from sklearn.linear_model import LogisticRegression


C:\Users\ankush\anacondanew\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\ankush\anacondanew\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
C:\Users\ankush\anacondanew\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import 

In [2]:
data=pd.read_csv('C:/Users/ankush/Desktop/2018_03.csv')

In [16]:
data.isnull().sum()


date train_id  stop_sequence                   from  from_id  \
0  2018-03-01     3805          1.000  New York Penn Station      105   
1  2018-03-01     3805          2.000  New York Penn Station      105   
2  2018-03-01     3805          3.000     Secaucus Upper Lvl    38187   
3  2018-03-01     3805          4.000    Newark Penn Station      107   
4  2018-03-01     3805          5.000         Newark Airport    37953   

                      to  to_id       scheduled_time          actual_time  \
0  New York Penn Station    105  2018-03-02 01:22:00  2018-03-02 01:21:05   
1     Secaucus Upper Lvl  38187  2018-03-02 01:31:00  2018-03-02 01:31:08   
2    Newark Penn Station    107  2018-03-02 01:40:00  2018-03-02 01:40:07   
3         Newark Airport  37953  2018-03-02 01:45:00  2018-03-02 01:45:10   
4        North Elizabeth    109  2018-03-02 01:49:00  2018-03-02 01:49:10   

   delay_minutes    status              line        type  Delay_Category  
0          0.000  departed  Northeast Corrdr  NJ Transit               0  
1          0.133  departed  Northeast Corrdr  NJ Transit               1  
2          0.117  departed  Northeast Corrdr  NJ Transit               1  
3          0.167  departed  Northeast Corrdr  NJ Transit               1  
4          0.167  departed  Northeast Corrdr  NJ Transit               1

In [3]:
data=data.dropna(0)


In [4]:
data['Delay_Category']=np.where(data['delay_minutes']>0,1,0)


# Exploring the data

In [5]:
#X=data.drop(['Price','Date','Address','Propertycount'],axis=1)
X=pd.get_dummies(data.drop(['scheduled_time', 'actual_time', 'delay_minutes'], 1))
Y=data['Delay_Category']
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
#X = StandardScaler().fit_transform(X)
sm = SMOTE(random_state=2)
X_sampled,y_sampled = sm.fit_sample(X,Y)
X_train_sample,X_test_sample,y_train_sample,y_test_sample = train_test_split(X_sampled,y_sampled,test_size=.20)

This is a classification problem so we will now PCA for dimension reduction to get most of the variance in least variables as we can

# Dimension Reduction PCA

In [20]:
X_pca = PCA(n_components=5)
X_pca.fit(X_train_sample)
X_train_pca = X_pca.transform(X_train_sample)
X_test_pca = X_pca.transform(X_test_sample)
print(
    'The percentage of total variance in the dataset explained by each',
    'component from Sklearn PCA.\n',
    X_pca.explained_variance_ratio_
)

The percentage of total variance in the dataset explained by each component from Sklearn PCA.
 [5.98084081e-01 4.01915788e-01 1.12982863e-07 1.47602342e-09
 6.10182751e-10]


We have selected 5 components which are explaning most of the variance in the dataset.We will use all the classification models -Naive Bayes,KNN,Decision Tree,Random Forest, Linear Regression, Ridge Regression, Lasso Regression, SVC,GBR and fit the model with the data and check the accuracy of the model.First we will use gridsearch cv to get the best parameters and then the below techniques for each model and compare them-

Cross Validation

Classification_report

AUC

Confusion Matrix




# 1.Naive Bayes

In [15]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB() 
#Fitting the model with the train data
bnb = bnb.fit(X_train_pca, y_train_sample)
y_pred_bnb = bnb.predict(X_train_pca)


Accuracy: 0.9446848401880841


Since we have fitted the model with the data and we dont have any parameters to tune using gridsearch cv so we are only using Cross Validation
Classification_report,AUC,Confusion Matrix accuracy of the model

### Cross Validation

In [21]:
print("Training data accuracy for Naive Bayes: ",cross_val_score(bnb, X_train_pca, y_train_sample, cv=10))
print("Testing data accuracy Naive Bayes: ",cross_val_score(bnb, X_test_pca, y_test_sample, cv=10))

Training data accuracy for Naive Bayes:  [0.94476684 0.94551082 0.94580841 0.94473543 0.9425927  0.94396167
 0.94419975 0.94616232 0.94520996 0.94390048]
Testing data accuracy Naive Bayes:  [0.94417331 0.94572075 0.94667302 0.94703012 0.94453041 0.94381621
 0.94345238 0.94511905 0.9452381  0.94238095]


### AUC(Area Under the Curve)

In [22]:
from sklearn.metrics import roc_auc_score
print ("AUC Score for BNB :" ,roc_auc_score(y_train_sample, y_pred_bnb))

AUC Score for BNB : 0.9446707058518109


### Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
print(confusion_matrix(y_train_sample, y_pred_bnb))
print('Accuracy Score for BNB :',accuracy_score(y_train_sample, y_pred_bnb))

[[155079  12818]
 [  5769 162354]]
Accuracy Score for BNB : 0.9446848401880841


### Classification Report

In [24]:
from sklearn.metrics import classification_report
print("Classification Report for BNB:",classification_report(y_train_sample, y_pred_bnb))

Classification Report for BNB:              precision    recall  f1-score   support

          0       0.96      0.92      0.94    167897
          1       0.93      0.97      0.95    168123

avg / total       0.95      0.94      0.94    336020



# 2.KNN Classification 

In [25]:
#KNN
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_pca, y_train_sample)
y_pred_knn = knn_model.predict(X_train_pca)
params = {'n_neighbors':[5],
          'leaf_size':[1,2,3,5]
                  }
#Making models with hyper parameters sets
grid_class_knn = model_selection.GridSearchCV(knn_model, param_grid=params)
#Learning
grid_class_knn.fit(X_train_pca,y_train_sample)
#The best hyper parameters set

results = grid_class_knn.cv_results_
print(results.get('params'))
print(results.get('mean_test_score'))
print(results.get('mean_train_score'))
print("Best Hyper Parameters:\n",grid_class_knn.best_params_)
print(grid_class_knn.best_score_)
final_model = grid_class_knn.best_estimator_
print(final_model)

[{'leaf_size': 1, 'n_neighbors': 5}, {'leaf_size': 2, 'n_neighbors': 5}, {'leaf_size': 3, 'n_neighbors': 5}, {'leaf_size': 5, 'n_neighbors': 5}]
[0.99599726 0.99599726 0.99599726 0.99599726]
[0.99734837 0.99734837 0.99734837 0.99734837]
Best Hyper Parameters:
 {'leaf_size': 1, 'n_neighbors': 5}
0.9959972620677341
KNeighborsClassifier(algorithm='auto', leaf_size=1, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


C:\Users\ankush\anacondanew\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)


### Cross Validation

In [26]:
print("Training data accuracy for Naive Bayes: ",cross_val_score(grid_class_knn, X_train_pca, y_train_sample, cv=10))
print("Testing data accuracy Naive Bayes: ",cross_val_score(grid_class_knn, X_test_pca, y_test_sample, cv=10))

Training data accuracy for Naive Bayes:  [0.9969348  0.99717287 0.99711335 0.99687519 0.99672639 0.99705375
 0.99705375 0.99636916 0.99705366 0.99651796]
Testing data accuracy Naive Bayes:  [0.98690632 0.98714439 0.98559695 0.98762052 0.98714439 0.98607309
 0.99047619 0.98916667 0.99       0.98630952]


In [ ]:
from sklearn.metrics import roc_auc_score
print ("AUC Score for BNB :" ,roc_auc_score(y_train_sample, y_pred_bnb))